[tool.poetry]
name = "sta"
version = "0.1.0"
description = ""
authors = ["Jeremy Mann <jmann227@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
